version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./back/:/app/back:ro
      - ./front:/app/front:ro
    ports:
      - "88:80"

  app:
    image: webdevops/php:7.4-alpine
    volumes:
      - ./back:/app/back

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: pass

  node:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./front:/app