version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./back/:/app/back:ro
      - ./front:/app/front:ro
    ports:
      - "88:80"

  app:
    image: webdevops/php:7.4-alpine
    working_dir: /app/back
    volumes:
      - ./back:/app/back

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data

  node:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./front:/app

volumes:
  db-data: